name: DevSecOps Pipeline - End to End

on:
  push:
    branches:
      - rajendra

  workflow_dispatch:

jobs:

  code-quality:
    uses: ./.github/workflows/code-quaility.yml

  secrets:
    uses: ./.github/workflows/secrets-scan.yml
    secrets: inherit

  dependency:
    uses: ./.github/workflows/dependency-check.yml

  docker-validate:
    uses: ./.github/workflows/docker-lint.yml

  docker-image:
    uses: ./.github/workflows/image-scan.yml

  build-and-push:
    uses: ./.github/workflows/build-push.yml