name: DevSecOps Pipeline - End to End

on:
  push:
    branches:
      - rajendra

  workflow_dispatch:

jobs:
  code-quality:
    uses: ./.github/workflows/code-quaility.yml

  secrets:
    uses: ./.github/workflows/secrets-scan.yml
    secrets: inherit

  dependency:
    uses: ./.github/workflows/dependency-check.yml

  docker-validate:
    uses: ./.github/workflows/docker-lint.yml

  build-and-push:
    needs: 
       - code-quality
       - secrets
       - dependency
       - docker-validate
    uses: ./.github/workflows/build-push.yml
    secrets: inherit

  docker-image:
    needs: 
       - build-and-push 
       - docker-validate
    uses: ./.github/workflows/image-scan.yml
