name: Code Quality

on:
  workflow_call:

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.12","3.14"]

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt 

      - name: Run Flake8
        run: |
          flake8 app.py

      - name: Run Bandit SAST
        run: |
          bandit -r . \
            --exclude ./.git,./venv,./.venv \
            -ll \
            -f json \
            -o security_report.json
        continue-on-error: true

      - name: Display Bandit Results
        if: always()
        run: |
          cat security_report.json

      - name: Upload Bandit Report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: bandit-security-report
          path: security_report.json