name: Dependency Check

on:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup python
        uses: actions/setup-python@v7
        with:
            python-version: 3.14

      - name: Install pip audit
        run: pip install --no-cache-dir pip-audit 

      - name: Audit dependency
        run: pip-audit -r requirements.txt
